data:
  build: docker/data
  hostname: data
  domainname: localdomain
  volumes:
    - ../data-mount/var-lib-ckan:/var/lib/ckan
    - ../data-mount/etc-postgres:/etc/postgresql/9.3/main
    - ../data-mount/var-lib-postgres/:/var/lib/postgresql/9.3/main
    - ../data-mount/solr-data:/opt/solr/example/solr/ckan/data
    - ../data-mount/datapusher/:/root/datapusher

datapusher:
  build: _service-provider/
  hostname: datapusher
  domainname: localdomain
  volumes_from:
    - data
