data:
  build: docker/data
  hostname: data
  domainname: localdomain
  volumes:
    - /home/renato/projetos/aware/data-mount/var-lib-ckan:/var/lib/ckan
    - /home/renato/projetos/aware/data-mount/etc-postgres:/etc/postgresql/9.3/main
    - /home/renato/projetos/aware/data-mount/var-lib-postgres/:/var/lib/postgresql/9.3/main
    - /home/renato/projetos/aware/data-mount/solr-data:/opt/solr/example/solr/ckan/data

postgres:
  build: docker/postgres
  hostname: postgres
  domainname: localdomain
  volumes_from:
    - data
  environment:
    - CKAN_PASS=ckan_pass
    - DATASTORE_PASS=datastore_pass

solr:
  build: docker/solr
  hostname: solr
  domainname: localdomain
  volumes_from:
    - data

datapusher:
  build: _service-provider/_datapusher
  hostname: datapusher
  domainname: localdomain

ckan:
  build: .
  hostname: ckan
  domainname: localdomain
  links:
    - postgres:postgres
    - solr:solr
    - datapusher:datapusher
  command: /sbin/my_init
  volumes_from:
    - data
  volumes:
    - ./_config/custom_options.ini:/etc/ckan/default/custom_options.ini
    - ./_config/who.ini:/etc/ckan/default/who.ini
    - ./_etc/supervisor/conf.d:/etc/supervisor/conf.d

nginx:
  build: docker/nginx
  hostname: nginx
  domainname: localdomain
  links:
    - ckan:ckan
  ports:
    - "80:80"
  volumes:
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf



