data:
  build: docker/data
  hostname: data
  domainname: localdomain
  volumes:
    - ../data-mount/var-lib-ckan:/var/lib/ckan
    - ../data-mount/etc-postgres:/etc/postgresql/9.3/main
    - ../data-mount/var-lib-postgres/:/var/lib/postgresql/9.3/main
    - ../data-mount/solr-data:/opt/solr/example/solr/ckan/data

postgres:
  build: docker/postgres
  hostname: postgres
  domainname: localdomain
  volumes_from:
    - data
  environment:
    - CKAN_PASS=ckan_pass
    - DATASTORE_PASS=datastore_pass

